apiVersion : batch/v1
kind: Job
metadata:
  name: queue-consumer-job
  namespace: demospace
spec:
  parallelism: 3
  template:
    metadata:
      name: queue-consumer-job
    spec:
      containers:
      - name : queue-consumer-job
        image: rosariocannavo/tapdemoconsumer
        imagePullPolicy: "Always"
        env  :
          - name: BTALK_IP
            valueFrom:
              configMapKeyRef:
                name  : beanstalk-configmap
                key   : queue_url
      restartPolicy   : OnFailure